site_name: Calculation Docs

theme:
  name: "material"
  
plugins:
  - mkdocstrings
  
nav:
  - Calculation Docs: index.md
  - Tutoriais: tutorials.md
  - Guia MKDOCS: how-to-guides.md
  - Referências: references.md
  - Detalhamento: explanation.md