hide:
  - navigation
  - toc


site_name: ML Library Documentation

theme:
  name: "material"
  
plugins:
  - mkdocstrings

nav:
  - Functions Library: references_func.md
  - Templates ML: references_temp.md
